export const lessonOptions = [
  { id: "1", label: "Lesson 1" },
  { id: "2", label: "Lesson 2" },
  { id: "3", label: "Lesson 3" },
  { id: "4", label: "Lesson 4" },
  { id: "5", label: "Lesson 5" },
  { id: "6", label: "Lesson 6" },
  { id: "7", label: "Lesson 7" },
  { id: "8", label: "Lesson 8" },
  { id: "9", label: "Lesson 9" },
  { id: "10", label: "Lesson 10" },
  { id: "11", label: "Lesson 11" },
  { id: "12", label: "Lesson 12" },
  { id: "13", label: "Lesson 13" },
  { id: "14", label: "Lesson 14" },
  { id: "15", label: "Lesson 15" },
  { id: "16", label: "Lesson 16" },
];
